name: CI
"on":
  pull_request:
    branches:
      - main
jobs:
  - staging
  - dev
test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: pnpm
    - name: Install dependencies for testing
      run: pnpm install --frozen-lockfile
    - name: Run tests
build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: pnpm
    - name: Install dependencies for building
      run: pnpm install --frozen-lockfile
    - name: Lint code
      run: pnpm run lint
    - name: Build project
      run: pnpm run build
docker-build:
  runs-on: ubuntu-latest
  needs:
    - lint
    - test
    - build
  if: >-
    github.event_name == 'push' && github.ref == 'refs/heads/main' ||
    github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/dev'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Registry
      run: >-
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{
        secrets.DOCKER_USERNAME }} --password-stdin your-docker-registry-url
    - name: Build Docker image
      run: "docker build . -t your-image-name:latest"
    - name: Push Docker image
      run: "docker push your-image-name:latest"
